### PR TITLE
Updates to expected output from DarkBit_standalone_MSSM for models 1-9.

### PR DESCRIPTION
**Pull request by ankitbeniwal93**
This pull request changes the expected output from DarkBit_standalone_MSSM for models 1-9 in Tables 11/12 of DarkBit paper. The standalone now passes all tests for these models.

The "pole" = false in _DarkBit/examples/DarkBit_standalone_MSSM.cpp_ should be the default option (c.f. "pole" = true which should be used to reproduce values in Tables 11/12).

Note that 
1. "pole" = false option leads to discrepancies vs Tables 11/12 (as noted in issue #174 on patscott/gambit).
2. Use **DB_standalone_MSSM_checks** branch on patscott/gambit/ to link to gambit executable; this branch will be merged  into master via a pull request soon.

### CODE REVIEW

**Comment by andrewfowlie** [comment]
This isn't what I was expecting. I thought you would change the gambit_bats yaml files to use the appropriate pole option to reproduce the output from the DarkBit paper in the tests.

Instead, we have changed the expected output.

Are you sure this is what we want?

**Comment by ankitbeniwal93** [comment]
@andrewfowlie: I paste a reply from @patscott from issue #174 on patscott/gambit/ here:

> the correct behaviour is with pole=false. It's just that the numbers in the DarkBit paper were computed before we knew that. So now that we know that the discrepancy is due to this setting, someone should update the BATS tests to test against the updated correct results **(with pole=false, not the ones in the DarkBit paper)**, and add a comment in the standalone next to this setting that reminds people that the results will not agree with the DarkBit paper unless this setting is modified.

Re: appropriate pole option, I've checked in my local copy that _pole = true_ reproduces tables 11/12 in DarkBit paper. 

Re: updates to a yaml file, I didn't find one for models 1-9. I thought I could use the _standalones.bats_ file directly to test the standalone for all models. Is this not correct?

**Comment by andrewfowlie** [comment]
> Re: updates to a yaml file, I didn't find one for models 1-9. I thought I could use the standalones.bats file directly to test the standalone for all models. Is this not correct?

Sorry you're right, these tests are for the standalones, which don't use the yamls. Alright, let's merge it.

**Comment by ankitbeniwal93** [comment]
@andrewfowlie: feel free to test it out; it works for me without any issues, i.e., no test fails.

**Pull request merged**
